# Generated by Django 3.0.5 on 2020-04-02 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='user_validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.CharField(max_length=15)),
                ('claim', models.CharField(max_length=15)),
                ('claim_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation_app.claim')),
            ],
        ),
    ]
